FROM python:3.9.12-slim-buster

WORKDIR /python-docker

COPY ./worker/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./worker ./

ARG experiment_files
COPY ${experiment_files}/* ./files/

CMD ["python3", "main.py"]
