FROM python:3.9.12-slim-buster

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./app ./app
COPY ./images ./images
COPY ./worker ./worker
COPY ./start.py .

CMD ["python3", "start.py"]
